alter table public.registrations
  add column if not exists target_weight numeric(6, 2),
  add column if not exists program_status text not null default 'registered',
  add column if not exists started_at timestamptz,
  add column if not exists ended_at timestamptz,
  add column if not exists test_mode boolean not null default true;

alter table public.registrations
  drop constraint if exists registrations_target_weight_check;
alter table public.registrations
  add constraint registrations_target_weight_check
  check (
    target_weight is null
    or (target_weight > 0 and target_weight <= 999.9 and target_weight < weight)
  );

alter table public.registrations
  drop constraint if exists registrations_program_status_check;
alter table public.registrations
  add constraint registrations_program_status_check
  check (program_status in ('registered', 'active', 'continuing', 'ended'));

alter table public.weight_entries
  add column if not exists checkin_type text,
  add column if not exists feedback_sent_at timestamptz;

create unique index if not exists weight_entries_registration_checkin_key
  on public.weight_entries (registration_id, checkin_type)
  where checkin_type is not null;

create table if not exists public.scheduled_program_emails (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references public.registrations(id) on delete cascade,
  milestone text not null,
  resend_email_id text,
  scheduled_for timestamptz not null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'cancel_requested', 'canceled')),
  created_at timestamptz not null default now(),
  unique (registration_id, milestone)
);

alter table public.scheduled_program_emails enable row level security;
revoke all on table public.scheduled_program_emails from anon, authenticated;
revoke all on sequence public.scheduled_program_emails_id_seq from anon, authenticated;

drop function if exists public.add_diet_weight_entry(text, numeric);
drop function if exists public.get_diet_weight_history(text);

create function public.get_diet_weight_history(access_token text)
returns table (
  weight numeric,
  recorded_at timestamptz,
  checkin_type text
)
language sql
security definer
set search_path = ''
as $$
  select w.weight, w.recorded_at, w.checkin_type
  from public.weight_entries as w
  join public.registrations as r on r.id = w.registration_id
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex')
  order by w.recorded_at asc, w.id asc;
$$;

create or replace function public.get_diet_program_profile(access_token text)
returns table (
  starting_weight numeric,
  target_weight numeric,
  current_weight numeric,
  plan text,
  tags text,
  program_status text,
  started_at timestamptz,
  test_mode boolean,
  latest_checkin text
)
language sql
security definer
set search_path = ''
as $$
  select
    r.weight,
    r.target_weight,
    latest.weight,
    r.plan,
    r.tags,
    r.program_status,
    r.started_at,
    r.test_mode,
    latest.checkin_type
  from public.registrations as r
  join lateral (
    select w.weight, w.checkin_type
    from public.weight_entries as w
    where w.registration_id = r.id
    order by w.recorded_at desc, w.id desc
    limit 1
  ) as latest on true
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex');
$$;

create or replace function public.start_diet_program(access_token text)
returns table (
  recipient_email text,
  starting_weight numeric,
  target_weight numeric,
  plan text,
  tags text,
  test_mode boolean,
  newly_started boolean,
  scheduled_milestones text[]
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
  was_new boolean;
begin
  select r.id, (r.started_at is null)
  into target_id, was_new
  from public.registrations as r
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex');

  if target_id is null then
    raise exception using errcode = 'P0002', message = 'Invalid access token';
  end if;

  update public.registrations as r
  set
    started_at = coalesce(r.started_at, now()),
    ended_at = null,
    program_status = case when r.program_status = 'registered' then 'active' else r.program_status end
  where r.id = target_id;

  return query
  select
    r.email,
    r.weight,
    r.target_weight,
    r.plan,
    r.tags,
    r.test_mode,
    was_new,
    coalesce(
      (select array_agg(s.milestone order by s.id)
       from public.scheduled_program_emails as s
       where s.registration_id = r.id and s.status = 'scheduled'),
      array[]::text[]
    )
  from public.registrations as r
  where r.id = target_id;
end;
$$;

create or replace function public.save_diet_scheduled_email(
  access_token text,
  email_milestone text,
  resend_id text,
  send_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  select r.id into target_id
  from public.registrations as r
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex');
  if target_id is null then
    raise exception using errcode = 'P0002', message = 'Invalid access token';
  end if;

  insert into public.scheduled_program_emails (
    registration_id, milestone, resend_email_id, scheduled_for, status
  )
  values (target_id, email_milestone, resend_id, send_at, 'scheduled')
  on conflict (registration_id, milestone) do update
  set
    resend_email_id = excluded.resend_email_id,
    scheduled_for = excluded.scheduled_for,
    status = 'scheduled';
end;
$$;

create or replace function public.add_diet_weight_entry(
  access_token text,
  new_weight numeric,
  entry_checkin text default null
)
returns table (
  weight numeric,
  recorded_at timestamptz,
  feedback_sent_at timestamptz,
  recipient_email text,
  starting_weight numeric,
  target_weight numeric,
  current_weight numeric,
  plan text,
  tags text,
  test_mode boolean,
  program_status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
  entry_id bigint;
begin
  if new_weight is null or new_weight <= 0 or new_weight > 999.9 then
    raise exception using errcode = '22023', message = 'Invalid weight';
  end if;
  if entry_checkin is not null
    and entry_checkin !~ '^(week1|month1|month2|month3|continue_[0-9]+)$' then
    raise exception using errcode = '22023', message = 'Invalid check-in type';
  end if;

  select r.id into target_id
  from public.registrations as r
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex')
    and r.program_status in ('active', 'continuing');
  if target_id is null then
    raise exception using errcode = 'P0002', message = 'Inactive or invalid program';
  end if;

  if entry_checkin is not null then
    select w.id into entry_id
    from public.weight_entries as w
    where w.registration_id = target_id and w.checkin_type = entry_checkin;
  end if;

  if entry_id is null then
    insert into public.weight_entries (registration_id, weight, checkin_type)
    values (target_id, round(new_weight, 1), entry_checkin)
    returning id into entry_id;
  end if;

  return query
  select
    w.weight,
    w.recorded_at,
    w.feedback_sent_at,
    r.email,
    r.weight,
    r.target_weight,
    w.weight,
    r.plan,
    r.tags,
    r.test_mode,
    r.program_status
  from public.weight_entries as w
  join public.registrations as r on r.id = w.registration_id
  where w.id = entry_id;
end;
$$;

create or replace function public.mark_diet_feedback_sent(
  access_token text,
  entry_checkin text
)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.weight_entries as w
  set feedback_sent_at = now()
  from public.registrations as r
  where w.registration_id = r.id
    and w.checkin_type = entry_checkin
    and r.access_token_hash =
      encode(sha256(convert_to(access_token, 'UTF8')), 'hex');
$$;

create or replace function public.stop_diet_program(access_token text)
returns table (
  milestone text,
  resend_email_id text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  select r.id into target_id
  from public.registrations as r
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex');
  if target_id is null then
    raise exception using errcode = 'P0002', message = 'Invalid access token';
  end if;

  update public.registrations as r
  set program_status = 'ended', ended_at = now()
  where r.id = target_id;

  return query
  update public.scheduled_program_emails as s
  set status = 'cancel_requested'
  where s.registration_id = target_id
    and s.status = 'scheduled'
    and s.scheduled_for > now()
  returning s.milestone, s.resend_email_id;
end;
$$;

create or replace function public.mark_diet_emails_canceled(
  access_token text,
  email_milestones text[]
)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.scheduled_program_emails as s
  set status = 'canceled'
  from public.registrations as r
  where s.registration_id = r.id
    and s.milestone = any(email_milestones)
    and r.access_token_hash =
      encode(sha256(convert_to(access_token, 'UTF8')), 'hex');
$$;

create or replace function public.continue_diet_program(access_token text)
returns table (
  recipient_email text,
  current_weight numeric,
  target_weight numeric,
  test_mode boolean,
  maintenance boolean,
  scheduled_milestones text[]
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  select r.id into target_id
  from public.registrations as r
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex');
  if target_id is null then
    raise exception using errcode = 'P0002', message = 'Invalid access token';
  end if;

  update public.registrations as r
  set program_status = 'continuing', ended_at = null
  where r.id = target_id;

  return query
  select
    r.email,
    latest.weight,
    r.target_weight,
    r.test_mode,
    (latest.weight <= r.target_weight),
    coalesce(
      (select array_agg(s.milestone order by s.id)
       from public.scheduled_program_emails as s
       where s.registration_id = r.id and s.status = 'scheduled'),
      array[]::text[]
    )
  from public.registrations as r
  join lateral (
    select w.weight
    from public.weight_entries as w
    where w.registration_id = r.id
    order by w.recorded_at desc, w.id desc
    limit 1
  ) as latest on true
  where r.id = target_id;
end;
$$;

revoke all on function public.get_diet_program_profile(text) from public;
revoke all on function public.get_diet_weight_history(text) from public;
revoke all on function public.start_diet_program(text) from public;
revoke all on function public.save_diet_scheduled_email(text, text, text, timestamptz) from public;
revoke all on function public.add_diet_weight_entry(text, numeric, text) from public;
revoke all on function public.mark_diet_feedback_sent(text, text) from public;
revoke all on function public.stop_diet_program(text) from public;
revoke all on function public.mark_diet_emails_canceled(text, text[]) from public;
revoke all on function public.continue_diet_program(text) from public;

grant execute on function public.get_diet_program_profile(text) to anon, authenticated;
grant execute on function public.get_diet_weight_history(text) to anon, authenticated;
grant execute on function public.start_diet_program(text) to anon, authenticated;
grant execute on function public.save_diet_scheduled_email(text, text, text, timestamptz) to anon, authenticated;
grant execute on function public.add_diet_weight_entry(text, numeric, text) to anon, authenticated;
grant execute on function public.mark_diet_feedback_sent(text, text) to anon, authenticated;
grant execute on function public.stop_diet_program(text) to anon, authenticated;
grant execute on function public.mark_diet_emails_canceled(text, text[]) to anon, authenticated;
grant execute on function public.continue_diet_program(text) to anon, authenticated;
