alter table public.registrations
  add column if not exists access_token_hash text;

create unique index if not exists registrations_access_token_hash_key
  on public.registrations (access_token_hash)
  where access_token_hash is not null;

create table if not exists public.weight_entries (
  id bigint generated by default as identity primary key,
  registration_id bigint not null references public.registrations(id) on delete cascade,
  weight numeric(6, 2) not null check (weight > 0 and weight <= 999.9),
  recorded_at timestamptz not null default now()
);

create index if not exists weight_entries_registration_recorded_idx
  on public.weight_entries (registration_id, recorded_at);

alter table public.weight_entries enable row level security;
revoke all on table public.weight_entries from anon, authenticated;
revoke all on sequence public.weight_entries_id_seq from anon, authenticated;

create or replace function public.record_initial_diet_weight()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.access_token_hash is not null and new.weight is not null then
    insert into public.weight_entries (registration_id, weight)
    values (new.id, new.weight);
  end if;
  return new;
end;
$$;

drop trigger if exists record_initial_diet_weight_after_insert on public.registrations;
create trigger record_initial_diet_weight_after_insert
after insert on public.registrations
for each row execute function public.record_initial_diet_weight();

create or replace function public.get_diet_weight_history(access_token text)
returns table (
  weight numeric,
  recorded_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  select w.weight, w.recorded_at
  from public.weight_entries as w
  join public.registrations as r on r.id = w.registration_id
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex')
  order by w.recorded_at asc, w.id asc;
$$;

create or replace function public.add_diet_weight_entry(
  access_token text,
  new_weight numeric
)
returns table (
  weight numeric,
  recorded_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_registration_id bigint;
begin
  if new_weight is null or new_weight <= 0 or new_weight > 999.9 then
    raise exception using
      errcode = '22023',
      message = 'Invalid weight';
  end if;

  select r.id into target_registration_id
  from public.registrations as r
  where r.access_token_hash =
    encode(sha256(convert_to(access_token, 'UTF8')), 'hex');

  if target_registration_id is null then
    raise exception using
      errcode = 'P0002',
      message = 'Invalid access token';
  end if;

  return query
    insert into public.weight_entries (registration_id, weight)
    values (target_registration_id, round(new_weight, 1))
    returning weight_entries.weight, weight_entries.recorded_at;
end;
$$;

revoke all on function public.get_diet_weight_history(text) from public;
revoke all on function public.add_diet_weight_entry(text, numeric) from public;
grant execute on function public.get_diet_weight_history(text) to anon, authenticated;
grant execute on function public.add_diet_weight_entry(text, numeric) to anon, authenticated;
