create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  email text not null check (char_length(email) between 3 and 320),
  weight numeric(6, 2) check (weight is null or weight > 0),
  plan text not null default '',
  summary text not null default '',
  tags text not null default '',
  registered_at timestamptz not null default now()
);

alter table public.registrations enable row level security;

revoke all on table public.registrations from anon, authenticated;
grant insert on table public.registrations to anon, authenticated;
grant usage, select on sequence public.registrations_id_seq to anon, authenticated;

drop policy if exists "allow public registration inserts" on public.registrations;
create policy "allow public registration inserts"
on public.registrations
for insert
to anon, authenticated
with check (
  char_length(email) between 3 and 320
  and char_length(plan) <= 500
  and char_length(summary) <= 20000
  and char_length(tags) <= 2000
);

create or replace function public.get_diet_registrations(admin_password text)
returns table (
  email text,
  weight numeric,
  plan text,
  summary text,
  tags text,
  registered_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if encode(sha256(convert_to(admin_password, 'UTF8')), 'hex')
    <> '6ef6a24b912e39664050636e1c323b9dcc579ff82c656a424bc83151c49964e7' then
    raise exception using
      errcode = '28000',
      message = 'Invalid admin password';
  end if;

  return query
    select
      r.email,
      r.weight,
      r.plan,
      r.summary,
      r.tags,
      r.registered_at
    from public.registrations as r
    order by r.registered_at desc
    limit 100;
end;
$$;

revoke all on function public.get_diet_registrations(text) from public;
grant execute on function public.get_diet_registrations(text) to anon, authenticated;
